
name: test env

on:
  workflow_call:
   outputs:
      args:
        value: ${{ jobs.format.outputs.output1 }}
  workflow_dispatch:
  
env: 
  URL: https://google.com?test=3423&tutu=ewrwmec
  URL3: https://tabuleo.com
  TUTU: 342j29j0ddj239jd0233

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.return.outputs.args }}
    steps:
      - uses: actions/checkout@v2
      
      - run: echo $JSON | jq -r 'keys[] as $k | "\($k)=\(.[$k])"'
        env:
          JSON: ${{ toJSON(env) }}
      
      - run: echo "${{toJSON(env)}}" > test.json
      
      - run: cat test.json
      
      - name: Return env
        id: return
        run: echo "::set-output name=args::$(cat test.json | base64)"
