
name: test env

on:
  workflow_call:
   outputs:
      args:
        value: ${{ jobs.format.outputs.output1 }}
  workflow_dispatch:
  
env: 
  URL: https://google.com?test=3423&tutu=ewrwmec
  URL3: https://tabuleo.com
  TUTU: 342j29j0ddj239jd0233

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.return.outputs.args }}
    steps:
      - uses: actions/checkout@v2
      
      - run: echo $JSON | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' > test.json
        env:
          JSON: ${{ toJSON(env) }}

      - run: cat test.json
      
      - name: encrypt file
        run: openssl enc -aes-256-cbc -nosalt -e -in test.json -out file.enc -K '2222233333232323' -iv '5a04ec902686fb05a6b7a338b6e07760'
      
      - run: echo "action_state=yellow" >> $GITHUB_ENV
      
      - uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: file.enc
          
      - name: Return env
        id: return
        run: echo "::set-output name=args::fogmdfomdfmppmmdopggdopmf"
