
name: test env

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
env: 
  URL: https://google.com?test=3423&tutu=ewrwmec
  URL3: https://tabuleo.com
  TUTU: 342j29j0ddj239jd0233

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: echo $JSON | jq -r 'keys[] as $k | "export \($k)=\(.[$k])"'
        env:
          JSON: ${{ toJSON(env) }}
          
      - run: jq --help
          
      - run: cat test2.json
      
      - run: echo "${{toJSON(env)}}" > test.json
      
      - run: cat test.json
