name: Format Vault secrets to args and env

on:
  push:
    branches: [ main ]
    
jobs:
  test:
    uses: ./.github/workflows/test.yml
    
  format:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      
      - run: echo "${{ env.action_state }}" # This will output 'yellow'
      - run: echo "${{ needs.test.outputs.args }}"
      
      - uses: actions/download-artifact@v2
        with:
          name: test-artifact
          path: test.json
          
      - run: cat test.json
