
name: test env

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
env: 
  URL: https://google.com?test=3423&tutu=ewrwmec

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: echo $JSON
        env:
          JSON: ${{ toJSON(env) }}
          
      - run: echo "${{toJSON(env)}}" > test.json
      
      - run: cat test.json
