name: Format Vault secrets to args and env

on:
  push:
    branches: [ main ]
    
jobs:
  test:
    uses: ./.github/workflows/test.yml
  
  test2:
    uses: ./.github/workflows/test3.yml
    
  format:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      
      - run: echo "${{ env.action_state }}" # This will output 'yellow'
      - run: echo "${{ needs.test.outputs.args }}"
      
      - uses: actions/download-artifact@v2
        with:
          name: test-artifact
          path: .
      
      - run: openssl enc -aes-256-cbc -nosalt -d -in file.enc -out test.json -K '2222233333232323' -iv '5a04ec902686fb05a6b7a338b6e07760'
          
      - run: cat test.json
